import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  header,
}: Readonly<{
  children: React.ReactNode
  header: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="w-full overflow-x-hidden">
        {header}
        {children}
      </body>
    </html>
  )
}
