import type { Metadata } from "next"
import AppProviders from "@/providers/AppProviders"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  header,
  footer,
}: Readonly<{
  children: React.ReactNode
  header: React.ReactNode
  footer: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden relative">
        <AppProviders>
          <div className="absolute size-full bg-[url('/food-pattern-light.jpg')] bg-repeat bg-contain bg-center opacity-[7%] -z-20"></div>
          {header}
          {children}
          {footer}
        </AppProviders>
      </body>
    </html>
  )
}
